### PR TITLE
add yitzchak

### PR DESCRIPTION
**Pull request by vindarel**
Hello @yitzchak, shall I merge as is?

### CODE REVIEW

**Comment by yitzchak** [comment]
Can you add my middle initial "W."? You can also list some other projects that might be of interest to the lisp community. There are others, but they are more specialized, chemistry, math etc.

- shasht: https://github.com/yitzchak/shasht
- cytoscape-clj: https://github.com/yitzchak/cytoscape-clj

Docs for cytoscape-clj will be up soon.

**Comment by vindarel** [comment]
added the W. and shasht. I don't intent to list all projects but the main 3/4 (should that change?), so the cl-jupyter plugin can be advertised from the hom cl-jupyter repo.

**Comment by yitzchak** [comment]
@vindarel Thanks!

**Comment by vindarel** [comment]
My pleasure. Keep up the good lisping!

**Pull request merged**
